<script setup>
import { DateTime } from "luxon";

definePageMeta({
  layout: "yard",
  middleware: ["require-auth", "require-yard"],
});

const client = useSupabaseClient();
const invoices = useState("invoices", () => []);
const yard = useState("yard");
const profile = useState("profile");

const { data: invoiceData, error: invoiceDataError } = await client
  .from("invoices")
  .select()
  .eq("yard_id", yard.value.id)
  .eq("client_id", profile.value.id)
  .filter("published", "is", true)
  .order("created_at", { ascending: false });

if (invoiceData) {
  invoices.value = invoiceData;
  console.log(invoices.value);
}
</script>

<template>
  <div class="w-full">
    <PageHeading
      title="My Invoices"
      description="A list of all the invoices you have received from the yard owner."
    >
    </PageHeading>
    <!-- Empty State -->
    <div
      v-if="invoices.length === 0"
      class="flex h-[calc(100vh-4rem)] w-full items-center justify-center"
    >
      <div class="text-center">
        <svg
          class="mx-auto h-12 w-12 text-gray-400"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path
            vector-effect="non-scaling-stroke"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"
          />
        </svg>
        <h3 class="mt-2 text-sm font-medium text-gray-900">No Invoices yet</h3>
        <p class="mt-1 px-10 text-sm text-gray-500">
          You have no invoices to display. Invoices will be displayed here<br />
          once they have been generated by the yard owner after each billing
          date.
        </p>
      </div>
    </div>
    <div v-else class="p-0 sm:p-6 md:h-screen md:overflow-y-auto lg:p-8">
      <NuxtLink
        v-for="invoice in invoices"
        :key="invoice.id"
        :to="`/yard/invoices/${invoice.id * 36}`"
        target="_blank"
        class="mb-4 flex items-center justify-between rounded-lg border transition-all duration-300 ease-in-out hover:cursor-pointer hover:shadow-lg"
        :class="{
          'bg-gray-50': invoice.published,
          'bg-gray-50': !invoice.published,
        }"
      >
        <div class="flex items-center">
          <UIcon name="i-heroicons-document" class="mx-4 h-8 w-8" />
          <div class="py-4 pr-4">
            <ClientOnly>
              <p>
                {{ DateTime.fromISO(invoice.end_date).toLocaleString() }}
              </p>
            </ClientOnly>
          </div>
          <span
            v-if="invoice.paid === false"
            class="inline-flex items-center rounded-full bg-red-100 px-2.5 py-0.5 text-xs font-medium text-red-800"
            >Unpaid</span
          >
          <span
            v-else
            class="inline-flex items-center rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800"
            >Paid</span
          >
        </div>

        <div class="pl-4">
          <UIcon name="i-heroicons-chevron-right-solid" class="mr-4 h-8 w-8" />
        </div>
      </NuxtLink>
    </div>
  </div>
</template>
