<script setup>
import { DateTime } from "luxon";

defineEmits(["back"]);

const client = useSupabaseClient();
const horse = useState("horse");
const invoices = useState("invoices", () => []);

const { data: invoiceData, error: invoiceDataError } = await client
  .from("invoices")
  .select("*")
  .eq("horse_id", horse.value.id)
  .filter("published", "is", true)
  .order("created_at", { ascending: false });

if (invoiceData) {
  invoices.value = invoiceData;
}
</script>

<template>
  <div>
    <div class="mb-5 border-b pb-5 sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-xl font-semibold text-gray-900">Invoces</h1>
        <p class="mt-2 text-sm text-gray-700">
          A list of all your previous invoces.
        </p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <button
          @click="$emit('back')"
          type="button"
          class="mr-2 inline-flex items-center justify-center rounded-md border bg-white px-4 py-2 text-sm font-medium hover:bg-gray-50 focus:outline-none sm:w-auto"
        >
          Back
        </button>
      </div>
    </div>
    <!-- Empty State -->
    <div
      v-if="invoices.length === 0"
      class="my-20 flex w-full items-center justify-center"
    >
      <div class="text-center">
        <svg
          class="mx-auto h-12 w-12 text-gray-400"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          aria-hidden="true"
        >
          <path
            vector-effect="non-scaling-stroke"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"
          />
        </svg>
        <h3 class="mt-2 text-sm font-medium text-gray-900">No Invoices yet</h3>
        <p class="mt-1 px-10 text-sm text-gray-500">
          You have no invoices to display. Invoices will be displayed here<br />
          once they have been generated by the yard owner after each billing
          date.
        </p>
      </div>
    </div>
    <NuxtLink
      v-else
      v-for="invoice in invoices"
      :key="invoice.id"
      :to="`/yard/invoices/${invoice.id * 36}`"
      target="_blank"
      class="mb-4 flex items-center justify-between rounded-lg border transition-all duration-300 ease-in-out hover:cursor-pointer hover:shadow-lg"
      :class="{
        'bg-gray-50': invoice.published,
        'bg-gray-50': !invoice.published,
      }"
    >
      <div class="flex items-center">
        <icon name="heroicons:document" class="mx-4 h-8 w-8" />
        <div class="py-4 pr-4">
          <p>
            {{ DateTime.fromISO(invoice.end_date).toFormat("DDDD") }}
          </p>
        </div>
        <span
          v-if="invoice.paid === false"
          class="inline-flex items-center rounded-full bg-red-100 px-2.5 py-0.5 text-xs font-medium text-red-800"
          >Unpaid</span
        >
        <span
          v-else
          class="inline-flex items-center rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-medium text-green-800"
          >Paid</span
        >
      </div>

      <div class="pl-4">
        <icon name="heroicons:chevron-right-solid" class="mr-4 h-8 w-8" />
        <!-- <button class="p-2 mr-2 shadow border rounded">
            View / Edit Items
          </button>
          <button class="p-2 mr-2 bg-indigo-500 text-white rounded">
            Create Invoice
          </button> -->
      </div>
    </NuxtLink>
  </div>
</template>
